### ISSUE TITLE
Program running error with 'sumogym_tester.py'

### ISSUE THREAD

**Issue by ShenZC25** [arpan-kusari/Naturalistic-SUMO-Gym#3] opened 2022-07-20 12:34 UTC
Dear Arpan,

Thank you very much for your hard work.But I had some problems when using it.

1. When I configured the installation environment and tried to run it, the first ERROR appeared, that is, the departure speed of all vehicles did not match the maximum allowable speed, like follows:

```
Warning: Choosing new speed factor 1.30 for vehicle 'genveh_7' to match departure speed 28.95 (max 21.76).
Error: Vehicle 'genveh_7' will not be able to depart using the given velocity (slow lane ahead)!
Warning: Choosing new speed factor 1.28 for vehicle 'genveh_9' to match departure speed 28.55 (max 21.80).
Warning: Choosing new speed factor 1.36 for vehicle 'genveh_10' to match departure speed 30.45 (max 19.88).
```

They all reported WARNING in SUMO GUI, and a few were error. I set all the speeds to RANDOM to solve this problem. Do you have any better solutions here?

2. Next, here's a more important question.After I set my own car ID and simulation time, the following error occurred：

```
D:\ProgramData\Anaconda3\envs\SUMO_gym\python.exe D:/PycharmProjects/SUMO_gym/sumogym_tester.py
Running simulation in urban  mode.
Please choose your ego vehicle ID (pressing enter only chooses 1st as ego): genveh_18
Please enter simulation time (pressing enter only runs till done): 50000
Traceback (most recent call last):
  File "D:/PycharmProjects/SUMO_gym/sumogym_tester.py", line 110, in <module>
    desired_lane = obs[0, 5]
TypeError: 'NoneType' object is not subscriptable
```

Why obs is 'NoneType' ?Do you have a good solution to it?

Thanks.

**Comment by pei-li-u-m** [comment] 2022-07-20 14:35
Hi,

1. The first issue is related to the speed limit of a lane and the speed of a vehicle. SUMO gives these warnings(errors) because the speed of a vehicle exceeds the speed limit of the lane it is assigned to. Setting random speed could be a quick fix. You can also try to increase the speed limit of lanes in the network.

2. I was not able to reproduce this error. Could you share more information about it? Did it happen in the beginning of the experiment or after several iterations? Also, some code snippets or screenshots could be helpful.

Thanks.

**Comment by ShenZC25** [comment] 2022-07-20 14:46
> Hi,
> 
> 1. The first issue is related to the speed limit of a lane and the speed of a vehicle. SUMO gives these warnings(errors) because the speed of a vehicle exceeds the speed limit of the lane it is assigned to. Setting random speed could be a quick fix. You can also try to increase the speed limit of lanes in the network.
> 2. I was not able to reproduce this error. Could you share more information about it? Did it happen in the beginning of the experiment or after several iterations? Also, some code snippets or screenshots could be helpful.
> 
> Thanks.

Hi,
Thank you for your patient answer.Regarding the second question, I'd like to provide the following screenshots.
![image](https://user-images.githubusercontent.com/89288084/180010814-ac0dd78c-bcc0-4ad7-bc28-ea1c1a4bfa3b.png)
![image](https://user-images.githubusercontent.com/89288084/180011813-56fca0e4-3d1e-4012-816c-601781bdd277.png)

As you can see, I gave an ID, but it seems that the program is running to

Curr _ pos = traci.vehicle.getposition (self.egoid) (probably on line 143)

Previously, only a few cars were loaded into the map, so the ID of the car could not be captured, resulting in LaneID being'', entering the if loop, returning the value of None, obs being NoneType, and an error occurred.

Could you please offer some suggestions? Thank you for your answer.

**Comment by pei-li-u-m** [comment] 2022-07-20 16:03
Hi,

Thanks for providing the information. I believe this is an out-of-network issue that happened to the ego vehicle. We have a checkpoint from Lines 450-482 in [sumo_gym.py](https://github.com/arpan-kusari/Naturalistic-SUMO-Gym/blob/main/sumo_gym/sumo_gym.py):

```
# sim check before traci update
if in_road == False or lane_id == "":
    info["debug"] = "Ego-vehicle is out of network"
    sim_check = True
elif self.egoID in traci.simulation.getCollidingVehiclesIDList():
    info["debug"] = "A crash happened to the Ego-vehicle"
    sim_check = True
else:
   .......
```

This captures the out-of-network issue and shuts down the program. So it takes care of the None observation issue as well.

I noticed that this error happened in the reset stage in your example? Did it happen at the beginning of the simulation then? Also, did you make any changes to the original code?

Thanks.

**Comment by arpan-kusari** [comment] 2022-07-20 18:01
Hi Shen, it seems for some reason, your code is starting with the ego-vehicle being out of network, which suggests some problem with either the road network or the ego vehicle initialization. You can check the net and route files but I dont think its a problem with the code. I am closing this issue but if you still keep on having problems, you can reopen it again.

**Closed as completed by arpan-kusari** 2022-07-20 18:01 UTC
